---
- name: Install ZooKeeper
  become: yes
  tasks:
    - name: Download ZooKeeper
      get_url:
        url: "https://downloads.apache.org/zookeeper/zookeeper-{{ zookeeper_version }}/apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz"
        dest: "/tmp/apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz"

    - name: Extract ZooKeeper
      unarchive:
        src: "/tmp/apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz"
        dest: "/opt/"
        remote_src: yes

    - name: Symlink ZooKeeper
      file:
        src: "/opt/apache-zookeeper-{{ zookeeper_version }}-bin"
        dest: "/opt/zookeeper"
        state: link

    - name: Create ZooKeeper Data Directory
      file:
        path: /opt/zookeeper/data
        state: directory

    - name: Configure ZooKeeper
      copy:
        content: |
          tickTime=2000
          dataDir=/opt/zookeeper/data
          clientPort=2181
          initLimit=5
          syncLimit=2
          {% for host in groups['masters'] %}
          server.{{ loop.index }}={{ hostvars[host]['ansible_host'] }}:2888:3888
          {% endfor %}
        dest: /opt/zookeeper/conf/zoo.cfg

    - name: Create myid File
      copy:
        content: "{{ (groups['zookeepers'].index(inventory_hostname) + 1) | string }}"
        dest: /opt/zookeeper/data/myid

    - name: Start ZooKeeper
      shell: /opt/zookeeper/bin/zkServer.sh start
