---
- name: Setup Common Configuration
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  roles:
    - common

- name: Install and Configure ZooKeeper on Master Nodes
  hosts: masters
  become: yes
  vars_files:
    - vars.yml
  roles:
    - zookeeper

- name: Setup Spark Cluster
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  roles:
    - spark
