---
- name: Update apt and upgrade
  apt:
    update_cache: yes
    upgrade: dist

- name: Install dependencies
  apt:
    name:
      - openjdk-11-jdk
      - wget
    state: present

- name: Create spark group
  group:
    name: spark
    state: present

- name: Create spark user
  user:
    name: spark
    group: spark
    create_home: yes
    shell: /bin/bash
    password: "{{ 'root' | password_hash('sha512') }}"
    state: present

- name: Grant spark user sudo privileges
  copy:
    content: "spark ALL=(ALL) NOPASSWD:ALL"
    dest: /etc/sudoers.d/spark
    mode: '0440'